const express = require ('express')
require('dotenv').config()
const bodyParser = require('body-parser')
const cors = require('cors')
const companyRouter = require('./src/routes/company')
const locationRouter = require('./src/routes/location')
const skillRouter = require('./src/routes/skill')
const flanceRouter = require('./src/routes/freelance')
const expertRouter = require('./src/routes/expertise')
const expRouter = require('./src/routes/experience')
const portofolioRouter = require('./src/routes/portofolio')
const hireRouter = require('./src/routes/hire')
const engineerRouter = require('./src/routes/engineer')
const projectRouter = require('./src/routes/project')
const accountRouter = require('./src/routes/account')
const morgan = require('morgan')

const app = express()

app.use(bodyParser.urlencoded({extended:false}))
app.use('/company', companyRouter)
app.use('/location', locationRouter)
app.use('/skill', skillRouter)
app.use('/freelance', flanceRouter)
app.use('/expertise', expertRouter)
app.use('/experience', expRouter)
app.use('/portofolio', portofolioRouter)
app.use('/hire', hireRouter)
app.use('/engineer', engineerRouter)
app.use('/project', projectRouter)
app.use('/account', accountRouter )
app.use(cors())
app.use(morgan('dev'))

app.use((request, response, next)=>{
  response.header('Access-Control-Allow-Origin', '*')
  response.header('Access-Control-Allow-Headers','Origin, X-Requested-With, Content-Type, Accept, Authorization')
  next()
})

app.get('/', (_request, response) => {response.send('Android 1 Backend')})

app.listen(process.env.PORT, ()=>{
  console.log(`App Listen on Port${process.env.PORT}!`)
})
